### ISSUE TITLE
creating tinyshell manager

### ISSUE THREAD

**Issue by mafe0002** [prof3ssorSt3v3/tinyshell#1]
Hi Steve,
I got the error below when creating a tinyshell manager, 
 "tinyshell.min.js:1 Uncaught TypeError: e.addEventListener is not a function
    at s.<anonymous> (tinyshell.min.js:1)
    at Array.forEach (<anonymous>)
    at s.addEventListener (tinyshell.min.js:1)
    at HTMLDocument.init (index.js:15)"
I don't know what to do get rid of this. my Project is attached below, pls take a look at it.
[Tundra.zip](https://github.com/prof3ssorSt3v3/tinyshell/files/1728555/Tundra.zip)

Regards,
kemi

**Comment by prof3ssorSt3v3** [comment]
Hi Kemi,


This code:

let targets = document.querySelectorAll('.card');
        let mgr = new t$(targets);
//creates a new instance of tinyshell and adds an array of elements

        let target = document.querySelector('div');
        let tiny = new t$(target);

        mgr.addEventListener(t$.EventTypes.SWIPELEFT, app.deleteCard);


Is adding the tinyshell twice.


You should be doing this stuff inside the loop when adding the cards. You can't do it before the cards are loaded.


INSIDE the loop for your profile data, where you are creating your cards, do this:


let tiny = new t$(card);

tiny.addEventListener(t$.EventTypes.SWIPELEFT, app.deleteCard);

//card is the variable that holds the div for your card.


Steve



________________________________

**Comment by mafe0002** [comment]
Thanks Steve.
